### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by sekhr4u** [sivaakurati/student-kard#12]
not able to login as a student or parent, im using the credentials in the db script. only as a teacher or admin im able to login.

no error message being popped up for any wrong entries.

**Comment by raghuchowdareddy** [comment]
two things here i am suspecting..
1.see if student and parent has admin role as you used
sec:authorize="hasRole('ROLE_ADMIN')"> in menu.html
2.debug and see if the control coming to loadUserByUsername() of CustomDetailsServiceImpl.java
